module View.About.About exposing (body)

import Html exposing (Html)
import Html.Attributes exposing (class, href, target)
import Model.Anchor.Buyer as Buyer
import Model.Anchor.Seller as Seller
import Model.State as State exposing (State(..))
import Msg.Msg exposing (Msg)


body : Html Msg
body =
    let
        html =
            Html.div
                [ class "has-font-1"
                ]
                [ Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.div
                        [ class "mb-3"
                        ]
                        [ Html.text "a decentralized market place built on the "
                        , Html.a
                            [ class "has-sky-blue-text mb-6"
                            , href "https://solana.com/"
                            , target "_blank"
                            ]
                            [ Html.text "solana blockchain"
                            ]
                        ]
                    , Html.div
                        [ class "mb-3"
                        ]
                        [ Html.text
                            """
                            providing what we are calling the "right-to-download"
                            of exclusive audio & video releases from
                            """
                        , Html.a
                            [ class "has-sky-blue-text mb-6"
                            , href "https://somos.world/"
                            , target "_blank"
                            ]
                            [ Html.text "somos*"
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.a
                        [ class "has-sky-blue-text mb-6"
                        , State.href (Buy Buyer.WaitingForWallet)
                        ]
                        [ Html.text "purchasing"
                        ]
                    , Html.text " a digital asset:"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "proves ownership via blockchain"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "provides exclusive access to an encrypted URL for-download"
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.text "the download URL of a given digital asset"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "is generated in real-time from your solana key-pair"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "can only be generated by owners"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "is opened automatically by your browser & starts the download immediately"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "expires seconds after it was generated"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "can be re-generated as many times as you want as long as you don't "
                            , Html.a
                                [ class "has-sky-blue-text mb-6"
                                , State.href (Sell Seller.WaitingForWallet)
                                ]
                                [ Html.text "sell your ownership"
                                ]
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.text "because this is a download"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "you can burn the audio file(s) to a CD & drive around town with it"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "upload to your iPod or any digital audio player"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "email a copy to your friend"
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.text "each digital asset is limited in number"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "typically 100 in units or more"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "will never be uploaded or available anywhere else"
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.text "you can sell your right-to-download"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "via the market-place at a price that you set"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "adding speculative value to each digital asset"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text "providing you real equity"
                            ]
                        , Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text """creates an opportunity for those who missed the initial sale
                                & want to enjoy the exclusive release that you have
                                """
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2 mb-3"
                    ]
                    [ Html.text "because we license all of our music"
                    , Html.ul
                        []
                        [ Html.li
                            [ class "mb-3"
                            ]
                            [ check
                            , Html.text """you cannot upload these digital assets to spotify/youtube/etc because it will be
                                algorithmically found & taken down or prevented entirely
                                """
                            ]
                        ]
                    ]
                , Html.p
                    [ class "has-border-2 px-2 pt-2"
                    ]
                    [ Html.div
                        [ class "mb-3"
                        ]
                        [ Html.text "every transaction is facilitated by a "
                        , Html.a
                            [ class "has-sky-blue-text mb-6"
                            , href "https://github.com/bigtimetapin/somos-solana/blob/develop/programs/somos-solana/src/lib.rs"
                            , target "_blank"
                            ]
                            [ Html.text "custom developed"
                            ]
                        , Html.text " smart contract"
                        ]
                    ]
                ]
    in
    Html.div
        [ class "container mt-6"
        ]
        [ html
        ]


check : Html msg
check =
    Html.b
        [ class "has-spacing-1"
        ]
        [ Html.text "☑️"
        ]
